### ISSUE TITLE
gppskyblock no permission

### ISSUE THREAD

**Issue by wolfhound871** [KaiKikuchi/GriefPreventionPlus-SkyBlock#11]
players do not have permission to the /is setbiome {yourchoice} {biome}

**Comment by KaiKikuchi** [comment]
gppskyblock.setbiome.all or gppskyblock.setbiome.biomename are the permissions you are missing.

**Comment by wolfhound871** [comment]
ok thx kai i was unable to find the perms for the plugin anyplace thx for the help
