### ISSUE TITLE
WorldEdit issues 

### ISSUE THREAD

**Issue by CobaltSparkz** [KaiKikuchi/GriefPreventionPlus-SkyBlock#12]
Hey Kai,

I've seen a previous post that you labeled, but just wanted to chase this up - On forge servers, you must use the forge version of WE - This means that when the schematic of an island is loaded, things are missed, such as items in a chest - Is there any ETA on this being implemented into GPP-Skyblock?

Thanks!

Sparkz

**Comment by KaiKikuchi** [comment]
Hey. No I am sorry there isn't any ETA.  I have too much work. I usually prioritize projects if someone asks for them and make a consistent donation, basically "funding it".

Duplicates https://github.com/KaiKikuchi/GriefPreventionPlus-SkyBlock/issues/3
