### ISSUE TITLE
Build permissions outside of the island

### ISSUE THREAD

**Issue by xXBuilderBXx** [KaiKikuchi/GriefPreventionPlus-SkyBlock#15]
My players are able to build blocks outside of their island claim which should not happen but grief prevention is blocking them from destroying blocks but not blocking placing. Is there anyway to fix this? also can i stop them from leaving their island.

**Comment by KaiKikuchi** [comment]
GriefPreventionPlus, if set to disallow building and destroying blocks outside claims, won't allow that. Also, some mod may bypass this, and that's not fixable.

Also, using some mod, it's possible to bypass the island border.

**Comment by xXBuilderBXx** [comment]
Well for some reason players are able to build outside their claim (No mod used to place) on my skyfactory server and i dont know what the problem is.

**Comment by KaiKikuchi** [comment]
Ah also, players are able to go outside the island border because the permission is true by default: https://github.com/KaiKikuchi/GriefPreventionPlus-SkyBlock/blob/master/src/main/resources/plugin.yml#L27

**Comment by xXBuilderBXx** [comment]
I was not aware of that permission at all >_> ill check my config hang on

**Comment by KaiKikuchi** [comment]
Yeah, I just noticed the README lacks the permissions section. But usually you can find a list of permissions on the "plugin.yml" file.

**Comment by xXBuilderBXx** [comment]
I found the issue setting these both causes the issue
    DisabledWorlds:
    - world
    ClaimRequiredWorlds:
    - world

So i removed -world from disabledworlds and it fixed the issue
