### ISSUE TITLE
Permission nodes

### ISSUE THREAD

**Issue by LeXiMoLe97** [KaiKikuchi/GriefPreventionPlus-SkyBlock#18]
Hey there, is there a list of the permission nodes anywhere?

 I'm trying to make it so players cannot /is spawn to other players islands and I can't find the permission nodes.

Thanks :)

**Comment by Eufranio** [comment]
https://github.com/KaiKikuchi/GriefPreventionPlus-SkyBlock/blob/master/src/main/resources/plugin.yml

**Comment by LeXiMoLe97** [comment]
Wow thanks I am such a derp... I can't believe I didn't see that
