### ISSUE TITLE
How do you use this addon?

### ISSUE THREAD

**Issue by HorrisEllis** [KaiKikuchi/GriefPreventionPlus-SkyBlock#20]

**Comment by Eufranio** [comment]
In your plugins folder, just like any other plugin.

**Comment by HorrisEllis** [comment]
But there isn't a jar it downloads as a ZIP.

**Comment by Eufranio** [comment]
https://github.com/KaiKikuchi/GriefPreventionPlus-SkyBlock/releases

**Comment by HorrisEllis** [comment]
Thanks.
