### ISSUE TITLE
Error when creating an island

### ISSUE THREAD

**Issue by runescapejon** [KaiKikuchi/GriefPreventionPlus-SkyBlock#22]
Sometime's when a player is creating and island it give an error in console and spam it 
https://pastebin.com/pPHJzemP
this happens sometimes
I'm using Thermos Build 59
GPP: 13.3
GPP-Skyblock:  1.3.7

**Comment by Eufranio** [comment]
Build 59?

**Comment by runescapejon** [comment]
i had compile it way back then when gradle links didn't mess up

**Comment by jon100456** [comment]
@KaiKikuchi  i am having this same issue would you mind fixing this ? please
or will someone have to make funds to a fast fix ?

**Comment by Westus** [comment]
The same error.
I wonder when they make an update. It kind of is. https://github.com/KaiKikuchi/GriefPreventionPlus-SkyBlock/issues/14
```
02.07 02:54:22 [Server] WARN [GPPSkyBlock] Task #93 for GPPSkyBlock v1.3.7 generated an exception
02.07 02:54:22 [Server] INFO java.lang.NullPointerException
02.07 02:54:22 [Server] INFO at org.bukkit.Location.getChunk(Location.java:73) ~[Location.class:1.7.10-1614.58]
02.07 02:54:22 [Server] INFO at net.kaikk.mc.gpp.skyblock.SpawnTeleportTask.run(SpawnTeleportTask.java:23) ~[?:?]
02.07 02:54:22 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-1614.58]
02.07 02:54:22 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.58]
02.07 02:54:22 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
02.07 02:54:22 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
02.07 02:54:22 [Multicraft] Skipped 25 lines due to rate limit (30/s)
02.07 02:54:22 [Server] WARN [GPPSkyBlock] Task #93 for GPPSkyBlock v1.3.7 generated an exception
02.07 02:54:22 [Server] INFO java.lang.NullPointerException
02.07 02:54:22 [Server] INFO at org.bukkit.Location.getChunk(Location.java:73) ~[Location.class:1.7.10-1614.58]
02.07 02:54:22 [Server] INFO at net.kaikk.mc.gpp.skyblock.SpawnTeleportTask.run(SpawnTeleportTask.java:23) ~[?:?]
02.07 02:54:22 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-1614.58]
02.07 02:54:22 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.58]
02.07 02:54:22 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
02.07 02:54:22 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
02.07 02:54:22 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
02.07 02:54:22 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
02.07 02:54:22 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by KaiKikuchi** [comment]
Please try again with version 1.4

**Comment by runescapejon** [comment]
https://pastebin.com/byQ8g50T still null error
https://github.com/KaiKikuchi/GriefPreventionPlus-SkyBlock/blob/v.1.4/src/main/java/net/kaikk/mc/gpp/skyblock/SpawnTeleportTask.java#L23 it's pointing null there

**Comment by KaiKikuchi** [comment]
I'm quite sure Location#getChunk isn't supposed to return null.

Are you using a custom Thermos build?
Or some mod is messing with the chunk manager.

Anyway, we can try with a null check and hopefully the chunk manager will return the instance at some point...

**Comment by runescapejon** [comment]
https://pastebin.com/LxtQ6QQS still null it seem to happen when i or player do `/is spawn`

**Comment by KaiKikuchi** [comment]
The issue is server side... the exception is being thrown by Bukkit code. Again, it's probably caused by some mod on your server, or your Thermos version has some bug.

I'll add an exception suppression although the issue is not caused by this plugin and should be fixed elsewhere.

**Comment by KaiKikuchi** [comment]
https://github.com/KaiKikuchi/GriefPreventionPlus-SkyBlock/releases/tag/v.1.4.2

**Comment by runescapejon** [comment]
ah thanks this fix the spam i was having for months <3 
but will look into some of the mods that may have cause it thanks
