### ISSUE TITLE
How does this plugin work?

### ISSUE THREAD

**Issue by Westus** [KaiKikuchi/GriefPreventionPlus-SkyBlock#23]
I load the server and it's the usual world.

**Comment by KaiKikuchi** [comment]
You should check the plugin folder, especially the config.yml file.

This plugin is especially made for void worlds.

Make a schematic with WorldEdit, then put it on the plugins folder and be sure to set the file name on the config. Then you use the commands specified here: https://github.com/KaiKikuchi/GriefPreventionPlus-SkyBlock
