### ISSUE TITLE
Initial db connection is in the server thread 

### ISSUE THREAD

**Issue by Eufranio** [KaiKikuchi/GriefPreventionPlus-SkyBlock#25]
The initial data load is made in the server thread, so other plugins will only load when its finished. Why not run it async?

**Comment by KaiKikuchi** [comment]
The initial db connection is done on server startup, not while the server is already loaded, like all other plugins. The initial data load is supposed to take just few milliseconds and definitely not more than a second. Not sure why you're asking about complicating this plugin with something that is not necessary.

**Comment by Eufranio** [comment]
It takes like 15+ seconds here...

**Comment by KaiKikuchi** [comment]
Then there is something extremely wrong with your server.

This is on a very populated SkyFactory 2:
![image](https://user-images.githubusercontent.com/8842403/29025771-af7adc80-7b78-11e7-90c0-62e5b3f521bb.png)
