### ISSUE TITLE
Islands empty when newbiesAutoSpawn is enabled

### ISSUE THREAD

**Issue by Eufranio** [KaiKikuchi/GriefPreventionPlus-SkyBlock#26]
The islands are being generated empty (no schematic, but claim created successfully) when the `NewbiesAutoSpawn` config option is enabled.

**Comment by KaiKikuchi** [comment]
Are you sure this does not happen with the `NewbiesAutoSpawn` config option disabled?

**Comment by Eufranio** [comment]
With the option disabled, when the player runs /is spawn his island is created correctly. With it enabled, they join for the first time and fall in the void, the claim exists but the island does not. They have to use /is reset to generate the island.

**Comment by KaiKikuchi** [comment]
Try with https://github.com/KaiKikuchi/GriefPreventionPlus-SkyBlock/releases/tag/v.1.4.3

Please close this issue if fixed.

**Comment by Eufranio** [comment]
Fixed!
