### ISSUE TITLE
Players fall into the void when untrusted

### ISSUE THREAD

**Issue by Eufranio** [KaiKikuchi/GriefPreventionPlus-SkyBlock#28]
If a player is trusted on a island that players without entrytrust cant enter and is untrusted while standing in the island, he will be teleported from border to border, and if entrytrust is false by default, he wont be able to stand in the borders too. That way, when untrusted, the player will crash and/or fall into the void and die. I suggest sending the players to the server spawn when untrusted.

**Comment by KaiKikuchi** [comment]
You have to use /setworldspawn to set the world spawn point. They get teleported into the void because the vanilla spawn point has not been set.

**Comment by Eufranio** [comment]
The world of the islands is ONLY for islands, there is no official spawn nor server building there. Cant you allow teleport to the SERVER spawn instead the WORLD spawn?

**Comment by KaiKikuchi** [comment]
Then just make a 5x5 platform at -256, 64, -256 and set the world spawn there. Sorry but I cannot do that.

**Comment by Eufranio** [comment]
Ok then.
