### ISSUE TITLE
Players cannot go to their friends' islands when they're offline

### ISSUE THREAD

**Issue by Eufranio** [KaiKikuchi/GriefPreventionPlus-SkyBlock#30]
If playerA is trusted in the island of playerB, and playerB is offline, playerA cannot use `/is spawn playerB`, the command will reply saying that playerB doesn't have a island. When playerB is online, the command works just fine.

**Comment by Eufranio** [comment]
Looks like it only happens with non-premium players. I have a plugin called FastLogin that gives non-premium players a premium UUID (not generated from name), so they have the right UUID even after buying the game, without losing their items, I think that may be the cause...

**Comment by KaiKikuchi** [comment]
Sorry but I do not provide any support for non-premium servers/players.

**Comment by Eufranio** [comment]
This same problem happens when the server is in offline-mode and bungee is in online-mode, so that's not only related to non-premium servers.
