### ISSUE TITLE
Private Island permission

### ISSUE THREAD

**Issue by HeberonYT** [KaiKikuchi/GriefPreventionPlus-SkyBlock#32]
Hi.
I have a question, what is the permission node for the `/is private-public` command?
I've already seen the current permission nodes, but there are none that are related to it.
Thank you.

**Comment by KaiKikuchi** [comment]
Hello. `gppskyblock.private` is the permission. In the future, I suggest you using your permission plugin's "debug" feature (if available... I'm used to LuckPerms and Permissions Ex) to find out any permission you cannot find.

**Comment by HeberonYT** [comment]
Thanks for your response and for the advice.
