### ISSUE TITLE
Island creation schematic loading error

### ISSUE THREAD

**Issue by DamageDoctor** [KaiKikuchi/GriefPreventionPlus-SkyBlock#5]
I have been attempting to get a SkyBlock server up and running with GPP and GPP SkyBlock plugins but am experiencing an issue when attempting to create / reset an island. It appears that the WorldEdit is unable to load the sample schematic file provided with the plugin and errors out (images / logs attached).

<img width="615" alt="1462574314" src="https://cloud.githubusercontent.com/assets/19231914/15088127/20243d54-1433-11e6-89ef-8d28063c67c0.png">

`[08:37:03] [Server thread/INFO]: DamageDoctor issued server command: /is reset [08:37:07] [Server thread/INFO]: DamageDoctor issued server command: /is reset [08:37:07] [Server thread/INFO]: Generating DamageDoctor island at [world, 2283,747~2323,787] [08:37:07] [Server thread/INFO]: DamageDoctor island regeneration complete. [08:37:07] [Server thread/WARN]: java.util.zip.ZipException: too many length or distance symbols [08:37:07] [Server thread/WARN]: at java.util.zip.InflaterInputStream.read(Unknown Source) [08:37:07] [Server thread/WARN]: at java.util.zip.GZIPInputStream.read(Unknown Source) [08:37:07] [Server thread/WARN]: at java.util.zip.InflaterInputStream.read(Unknown Source) [08:37:07] [Server thread/WARN]: at java.io.DataInputStream.readByte(Unknown Source) [08:37:07] [Server thread/WARN]: at com.sk89q.jnbt.NBTInputStream.readNamedTag(NBTInputStream.java:73) [08:37:07] [Server thread/WARN]: at com.sk89q.jnbt.NBTInputStream.readNamedTag(NBTInputStream.java:62) [08:37:07] [Server thread/WARN]: at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.read(SchematicReader.java:75) [08:37:07] [Server thread/WARN]: at net.kaikk.mc.gpp.skyblock.ResetIslandTask.run(ResetIslandTask.java:86) [08:37:07] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) [08:37:07] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [08:37:07] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:895) [08:37:07] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [08:37:07] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831) [08:37:07] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683) [08:37:07] [Server thread/WARN]: at java.lang.Thread.run(Unknown Source)`

I have tested with a clean basic schematic saved by WE and also tested WE 6.0 and 6.1 but nothing seems to be working for me.

Am I missing something? Are specific versions of WE required?

Server is running:
MC 1.7.10 Infinity Evolved 1.1.0
Thermos-1.7.10-1614-55-server
GPP 12.23
GPP SkyBlock 1.3.3
WorldEdit 6.1

If there are any other logs / information that I can provide then please let me know.

**Comment by KaiKikuchi** [comment]
When running Cauldron-based servers, block ids changes randomly so the sample schematic I provided for Vanilla servers won't work. You have to make your own schematic.

**Comment by DamageDoctor** [comment]
I did try a schematic I created but it errors out. I will have to try it again and get the error output for you.

**Comment by LemADEC** [comment]
MCEdit doesn't recognize the provided schematic, it appears to be corrupted.
