### ISSUE TITLE
Error when using /is reset

### ISSUE THREAD

**Issue by matagin** [KaiKikuchi/GriefPreventionPlus-SkyBlock#7]
Whenever I run /is reset, it asks to confirm and I type it again and get the following exception. I am using the latest GPP and Thermos along with Worldedit 6.1.2. I made a new default.schematic of a SkyFactory 2.5 spawn.

http://pastebin.com/wPNMqi8R

**Comment by KaiKikuchi** [comment]
Sorry I've missed this issue. The issue is probably caused by the world being unloaded. Honestly I don't know how this is possible.
