### ISSUE TITLE
Islands Overwrite?

### ISSUE THREAD

**Issue by Time6628** [KaiKikuchi/GriefPreventionPlus-SkyBlock#9]
Any idea why this would happen?
![rip island](http://i.imgur.com/anVXOAH.png)

Had it happen a few times and it appears that there is a new island generating there, but it overwrites another island...

Using latest Thermos version and latest GPPSB version.

**Comment by KaiKikuchi** [comment]
I've seen something similar caused by Slime Islands. Be sure to disable all structure generations on the overworld.
